### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by jamesevickery** [jamesevickery/l293d#22]
At some point I should try and get this working in Python3 - currently development has all been 2.7

**Comment by jamesevickery** [comment]
@the-zebulan If you have time, would you be interested in starting to support Python 3?

**Comment by the-zebulan** [comment]
Sure, I'll try to get started on it tonight. I don't think it'll be that
hard (famous last words?).

**Comment by jamesevickery** [comment]
Tests seem to be working in Python 3 (although more need to be added, see #46)

Python 3.3, 3.4 and 3.5 are tested after each commit by TravisCI: https://travis-ci.org/jamesevickery/l293d
