### ISSUE TITLE
Travis CI linting

### ISSUE THREAD

**Issue by jamesevickery** [jamesevickery/l293d#23]
Tests for this library need to be set up in `.travis.yml`. This issue is a sequel to issue #16.

_Update:_ Tests should be added in the future, but this issue is now for linting, not tests

**Comment by surajnarwade** [comment]
which kind of test ?
can you please elaborate ?

**Comment by jamesevickery** [comment]
@surajnarwade I'm not sure to be honest - I have no experience in unit testing Python so thought I should try and add some tests 😕. Feel free to suggest anything if you have any ideas!

**Comment by surajnarwade** [comment]
I can add linting in travis for you, but can unit test utility also before that you have to write unit test for project

**Comment by jamesevickery** [comment]
@surajnarwade Linting would be very helpful thanks, do you recommend any particular Python unit test method?

**Comment by surajnarwade** [comment]
@jamesevickery , I am adding linting, go with simple unit testing
