### ISSUE TITLE
`setup.py` dependencies check

### ISSUE THREAD

**Issue by jamesevickery** [jamesevickery/l293d#24]
Before `setup.py` runs `install`, there should be a check to make sure the user has installed the dependencies. If they haven't, there can be an option to run `install` anyway, or abort the setup.

**Comment by surajnarwade** [comment]
hello, can you provide llist of dependencies so that I can contribute here ?

**Comment by jamesevickery** [comment]
@surajnarwade Thanks for the question, these should be installed:

- python-dev
- python-pip
- python-yaml

And there should be a warning if `RPi.GPIO` isn't installed or something, although if it's not installed then `driver.py` forces `test_mode = True`.

**Comment by surajnarwade** [comment]
can you label this issue as hacktoberfest?

**Comment by jamesevickery** [comment]
Reopening because I wanted `setup.py` to raise exceptions if importing the dependencies fails - but thanks for the change @surajnarwade!

**Comment by jamesevickery** [comment]
`ImportError` raised if `import yaml` fails. Exception message prompts user to install `python-yaml`.
