### ISSUE TITLE
Needs option to use BCM GPIO numbering

### ISSUE THREAD

**Issue by jamesevickery** [jamesevickery/l293d#5]
`BOARD` numbers are currently used, but user could _also_ have the option to use `BCM` numbering.

[Difference between `BOARD` and `BCM`](http://raspberrypi.stackexchange.com/questions/12966/what-is-the-difference-between-board-and-bcm-for-gpio-pin-numbering)

See [pinout.xyz](https://pinout.xyz/) for reference.

**Comment by SmithcS** [comment]
I'm not sure if I can assign myself to this, but I'll start working on this (and possibly issue #10) too

**Comment by jamesevickery** [comment]
@SmithcS Yeah it says you've assigned yourself :) Btw do you have Twitter or anything that I can IM you on? I can do #10 if you want, it's just a quick one: I wanted some of the code at the top of l293d.py to be put into methods.

**Comment by SmithcS** [comment]
I do have an ancient Twitter account ill bring back to life - I pass you my handle after I reset the password

**Comment by jamesevickery** [comment]
@SmithcS Okay thanks. Are you getting very far with this issue? Don't worry if not, I could do it soon

**Comment by SmithcS** [comment]
Hey - yep I started working on it Monday, however I've been busy at work
the past couple days. Sorry for leaving it in limbo, I'll probably finish
up with it sometime today/tomorrow.

**Comment by jamesevickery** [comment]
@SmithcS Could you get this checked in soon? There's some other stuff I want to do but it would be a nightmare trying to merge it 👍

**Comment by SmithcS** [comment]
Hey! Sorry that took so long. Just made a pull request for you to check in.

**Comment by jamesevickery** [comment]
Thanks! Btw I don't actually have L293D chips and motors with me for a while - if you've been using this library could you tell me if something stops working? I've only been developing while `test_mode = True`.

**Comment by SmithcS** [comment]
I have some motors but not the chips, I'll order some off of amazon.
