### ISSUE TITLE
Refactor clockwise and anticlockwise methods

### ISSUE THREAD

**Issue by jamesevickery** [jamesevickery/l293d#70]
`clockwise` and `anticlockwise` (and `stop`?) have code in common that could be refactored to use a new method

**Comment by alxwrd** [comment]
Am I ok to take this one?

**Comment by jamesevickery** [comment]
@alxwrd Of course 👍

**Comment by alxwrd** [comment]
Thanks.

Could I just check why only the `stop` method has `if not Config.get_test_mode()`? Will this need adding to `clockwise` and `anticlockwise`?

**Comment by jamesevickery** [comment]
@alxwrd Good question.

Looking back at the code, I don't think any of them need it. They call `drive_motor` which only makes GPIO calls when not in test mode. This '`if`' can probably be removed from `stop`.
